import { EMPLOYEE_STATUSES } from './employeeStatuses';

export const STATUS_TEXT_COLORS: Record<string, string> = {
    [EMPLOYEE_STATUSES.ACTIVE]: '#16A34A',         
    [EMPLOYEE_STATUSES.ON_VACATION]: '#EA580C',  
    [EMPLOYEE_STATUSES.SICK_LEAVE]: '#0284C7',   
    [EMPLOYEE_STATUSES.MATERNITY_LEAVE]: '#DB2777',  
    [EMPLOYEE_STATUSES.PROBATION]: '#CA8A04',      
    [EMPLOYEE_STATUSES.SUSPENDED]: '#52525B',      
    [EMPLOYEE_STATUSES.RESIGNED]: '#4B5563',       
    [EMPLOYEE_STATUSES.TERMINATED]: '#DC2626',     
    [EMPLOYEE_STATUSES.RETIRED]: '#6B7280',        
    [EMPLOYEE_STATUSES.FIRED]: '#DC2626',          
};